### ISSUE TITLE
Masonry/Snap should be renamed to be SnapKit/SnapKit

### ISSUE THREAD

**Issue by soleo** [mozilla/firefox-ios#1045]
"Masonry/Snap" is no longer valid, should be replaced with their new name. 

```
github "SnapKit/SnapKit"            >= 0.12.0
```

**Comment by AaronMT** [comment]
Just going through open issues, @sleroux, do we have to update our `cartfile`?

**Comment by sleroux** [comment]
Ya - we'll go through and update these dependencies for 2.0

**Comment by st3fan** [comment]
This has been done some time ago. Closing.
