### ISSUE TITLE
Save password dialog copy changes

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/firefox-ios#1068]
Currently in iOS Firefox:
![2015-09-14 17 56 19](https://cloud.githubusercontent.com/assets/68213/9887118/ff018404-5bbb-11e5-80c9-1d9fa4894446.png)

CURRENT:
* "Do you want to save the password for user@email.com on domain.org?"
* Yes
* Not now

PROPOSED
* "Save this login for domain.org?"
* Save Login
* Don’t Save

We are moving to a new design in desktop, although not as quickly as you are able to in mobile. It is not recommended to copy it completely (as the UI is more complex), but the copy should be enough
![saved-logins](https://cloud.githubusercontent.com/assets/68213/9887073/c4594aa8-5bbb-11e5-9deb-4c0f63bd188f.png)

Details:
https://mozilla.invisionapp.com/share/PC3Y0QSRK#/screens/96290118

Fennec currrently does, which we will change to "save":
* "Would you like <Fennec> to remember this login?"
* user@domain.org (clickable to edit dialog)
* Remember
* Never

**Comment by AaronMT** [comment]
Is this filed in Bugzilla?

**Comment by darrinhenein** [comment]
This one? https://bugzilla.mozilla.org/show_bug.cgi?id=1205047 <https://bugzilla.mozilla.org/show_bug.cgi?id=1205047>
