### ISSUE TITLE
Bookmarks not syncing

### ISSUE THREAD

**Issue by sammcj** [mozilla/firefox-ios#1071]
It appears that bookmarks don't actually seem to sync with your Firefox account.

I have tried:

- Killing the app and starting it again.
- Logging out and back into sync.
- Removing and reinstalling the app.

Syncing works between my various desktop Firefox browsers / computers.

![ff](https://cloud.githubusercontent.com/assets/862951/9893464/0709a60e-5c5c-11e5-8fe7-bbd49e746eb9.PNG)

**Comment by ncalexan** [comment]
Correct.  We're building this right now: https://bugzilla.mozilla.org/show_bug.cgi?id=1196238.  This issue is well tracked in our main bug tracker so I'm going to close it.  It'll land in the next few months.
