### ISSUE TITLE
Stock bookmarks can't be removed

### ISSUE THREAD

**Issue by sammcj** [mozilla/firefox-ios#1072]
There are two 'stock' bookmarks that can't be removed, this is annoying:

![ff](https://cloud.githubusercontent.com/assets/862951/9893464/0709a60e-5c5c-11e5-8fe7-bbd49e746eb9.PNG)

**Comment by AaronMT** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1205058

**Comment by st3fan** [comment]
This has been resolved as of 3.0
