### ISSUE TITLE
1Password extension not available in Firefox app

### ISSUE THREAD

**Issue by sammcj** [mozilla/firefox-ios#1074]
In most other applications the 1Password extension is available to fill in usernames and passwords securely, for some reason it is not available in the Firefox app.

I have checked in the '...' to ensure it isn't simply disabled.

![ff2](https://cloud.githubusercontent.com/assets/862951/9893563/030eb1c4-5c5d-11e5-8e16-6f3a8ace3b8a.PNG)

**Comment by tangyi** [comment]
I need 1password, too.

**Comment by AaronMT** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1162174

**Comment by st3fan** [comment]
Should be all good now.
