### ISSUE TITLE
On iPad, Firefox Sync login screen have scroll in it. I think it should be hidden to make it looks like native screen

### ISSUE THREAD

**Issue by ariefbayu** [mozilla/firefox-ios#1161]
Note: I'm using iPad mini 2 (retina) with iOS 9.0.2.

![img_0284](https://cloud.githubusercontent.com/assets/55084/10503959/7754e0a6-7325-11e5-85fa-b4fa067ae64f.PNG)
![img_0285](https://cloud.githubusercontent.com/assets/55084/10503960/7755fe46-7325-11e5-8a7a-a2a72e2b8bb2.PNG)

**Comment by ariefbayu** [comment]
oh, Firefox version 1.1 (1107)

**Comment by ncalexan** [comment]
Not a bad idea.  @vlad @stomlinson @jgruen: can one of you comment on
feasibility of tuning the fxa-content-server for known iDevice sizes and
file an fxa-content-server ticket if it's appropriate?

**Comment by vladikoff** [comment]
@ncalexan Sorry I just randomly saw this because I was not `@` mentioned properly. We will check this out.

cc @shane-tomlinson

**Comment by st3fan** [comment]
Pretty sure this does not happen anymore and that this was a bug related to us doing too much work for keyboard content offsets.

**Comment by shane-tomlinson** [comment]
This is still a problem on Firefox 5 for iOS w/ an iPad 2. Not sure whether this is a regression or not.
