### ISSUE TITLE
boorkmark syncing in v1.1 not working

### ISSUE THREAD

**Issue by winst0nsmith** [mozilla/firefox-ios#1258]
in the latest app store update it is claimed that bookmark syncing is a newly added feature. am i missing something? i still don't see my desktop bookmarks anywhere in the mobile app.

is this planned for the future? i need to have my desktop bookmarks available on my mobile app, otherwise a 3rd-party browser is pretty tough to use every day.

thanks for the great work up to this point though, i really appreciate it!

**Comment by st3fan** [comment]
Targeted for v5.0
