### ISSUE TITLE
Background app refresh

### ISSUE THREAD

**Issue by jesobreira** [mozilla/firefox-ios#1274]
From SuMo:

> I have Background App Refresh disabled... system-wide.  Yet, the Firefox app managed to get 8.6 hours of Background App Refresh...  and a significant chunk of my battery charge.  Firefox even used more battery than my Safari app, even though I BARELY used the Firefox app.  Firefox is NOT respecting the Background App Refresh setting...  it's going ahead and performing Background App Refresh—and tons of it, at that—despite the setting.
> This is not just Mozilla's fault, this is Apple's fault as well, because iOS is obviously not enforcing the Background App Refresh setting.
> I swiftly deleted Firefox after noticing this.  I may give it a second chance in the future, when Apple and Mozilla have gotten a chance to resolve this Background App Refresh issue.

([original post](https://support.mozilla.org/en-US/questions/1093664#answer-806103))

I asked the user to provide details about his environment. I'll post it here as soon as it's told.

Can someone confirm it?

**Comment by AaronMT** [comment]
Resolved. This can be closed (I don' have the powers).
