### ISSUE TITLE
Review hard-coded used of GCDWebServer port as a possible startup crasher

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/firefox-ios#1278]
I have had this fail once in the simulator trying to use the fixed port. I don't recall the workflow that triggered it. Has no one else seen this during development? I assume this isn't showing up in release builds.
https://github.com/mozilla/firefox-ios/blob/master/Client/Application/WebServer.swift#L22
Consider trying a range of ports before failing. 
IMHO seems like an unnecessary risk to rely on the network stack and process system to be bug-free on all iOS variants and properly release that port if the app crashes and is quickly restarted.

**Comment by st3fan** [comment]
If brave uses the same port number, please change it.

**Comment by garvankeeley** [comment]
Will do. Currently it searches for an unused port.
