### ISSUE TITLE
Why is the App icon have white BG? why not transparent like in android?

### ISSUE THREAD

**Issue by nikhiljohn10** [mozilla/firefox-ios#1291]

**Comment by thebnich** [comment]
From the [App Icon guidelines](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/AppIcons.html):

> **Avoid transparency.** An app icon should be opaque. If the icon’s boundaries are smaller than the recommended sizes—or you use transparency to create “see-through” areas—the resulting icon can appear to float on a dark background, which tends to look especially unattractive on the beautiful wallpapers that users choose.
