### ISSUE TITLE
Link bar is out of the screen

### ISSUE THREAD

**Issue by xsoh** [mozilla/firefox-ios#1305]
I'm using Firefox on my iPad mini 4 and the link bar gets out off the screen.
![image](https://cloud.githubusercontent.com/assets/871079/11399513/f806f692-9398-11e5-9bf9-fa6e705bded2.png)
I'm using iOS 9.1 and the OS language is Arabic so perhaps the issue because of the RTL layout

**Comment by AaronMT** [comment]
RTL support is not ready, we will be temporarily be removing Arabic https://bugzilla.mozilla.org/show_bug.cgi?id=1227618

**Comment by st3fan** [comment]
That will only mean we will not include the incomplete `ar` localization. We will still render badly on an RTL system as shown in the screenshot. I think we need to fix that, even without `ar` localizations.

**Comment by AaronMT** [comment]
High-level bug filed filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1229027

**Comment by st3fan** [comment]
Closing because we are tracking this in Bugzilla now.
