### ISSUE TITLE
Gmail thinks signins from firefox ios are from safari.

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/firefox-ios#1345]
This is gmail's responsibility obv. but wanted to document that this behavior is happening. Not sure if ff ios has a way to differentiate via user agent.

![gmail_signin](https://cloud.githubusercontent.com/assets/1844554/11696062/4653146a-9e67-11e5-908d-32a25c8b4230.png)

**Comment by danwalkowski** [comment]
Since iOS Firefox uses WKWebView, it reports as its user agent as Safari. Starting in iOS 9, this can be changed.

**Comment by st3fan** [comment]
Maybe we can ask Google to add our modified UA to their list for GMail. Marking as needing a bug in Bugzilla.

**Comment by varkor** [comment]
A bug to track this has been filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1291456.
