### ISSUE TITLE
Can't change MOZ_BUNDLE_ID in BaseConfig.xcconfig

### ISSUE THREAD

**Issue by ThangLuuQuoc** [mozilla/firefox-ios#1353]
Please help me,
After change MOZ_BUNDLE_ID in BaseConfig.xcconfig to my domain (replace org.mozilla to com.mydomain) i get error when build. 
Notes: I change all . *.entitlement and info.plist in ViewLater, ShareTo and SentTo to "com.mydomain";
and Cleaned and Rebuild still get error.
This is error message :+1: 
error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

		Embedded Binary Bundle Identifier:	org.mozilla.ios.Fennec.ShareTo
		Parent App Bundle Identifier:		com.mydomain.ios.Fennec

Thank you.

**Comment by AaronMT** [comment]
ping @sleroux

**Comment by sleroux** [comment]
Looks like we're not using MOZ_BUNDLE_ID for the app extensions right now. If you take a look at the Client target's build settings under "Product Bundle Identifier", it uses the MOZ_BUNDLE_ID correctly but the extensions don't. I've filed a bug to fix this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1236545.

**Comment by st3fan** [comment]
Closing now this is tracked in Bugzilla.
