### ISSUE TITLE
Swift compilation bug: TabTrayController.swift ~1 min to compile

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/firefox-ios#1482]
```xctool -scheme Client -jobs 1 build ```
reports:
Compile TabTrayController.swift (56710 ms)

MBP quad 2.6 i7. Very unusual for a file to take longer than 1s to compile.

Figuring out swift compilation buggery is a new domain for me, so any tips on this are appreciated.

**Comment by sleroux** [comment]
Hey Garvan,

I haven't done this yet but there some cool instructions here [1] to see what code paths are causing long compile times. We've definitely seen files have various compile times throughout development - especially with the Client target.

[1] http://irace.me/swift-profiling/

**Comment by garvankeeley** [comment]
Great tip Stefan! These are the top bad guys:
```
60237.7ms Client/Frontend/Browser/TabTrayController.swift:723:10	@objc dynamic func accessibilityScrollStatusForScrollView(scrollView: UIScrollView) -> String?
55905.3ms Client/Frontend/Browser/TabTrayController.swift:723:10	@objc dynamic func accessibilityScrollStatusForScrollView(scrollView: UIScrollView) -> String?
7178.8ms Storage/SQL/SQLiteLogins.swift:392:18	private func cloneMirrorToOverlay(whereClause whereClause: String?, args: Args?) -> Deferred<Maybe<Int>>
6186.3ms Storage/SQL/SQLiteLogins.swift:392:18	private func cloneMirrorToOverlay(whereClause whereClause: String?, args: Args?) -> Deferred<Maybe<Int>>
4249.7ms	 Storage/SQL/BrowserTable.swift:521:10	func drop(db: SQLiteDBConnection) -> Bool
3190.9ms Storage/SQL/BrowserTable.swift:521:10	func drop(db: SQLiteDBConnection) -> Bool
1004.4ms	 Sync/Synchronizers/LoginsSynchronizer.swift:28:6	func makeLoginRecord(login: Login) -> Record<LoginPayload>

```

**Comment by sleroux** [comment]
Holy smokes...
`@objc dynamic func accessibilityScrollStatusForScrollView(scrollView: UIScrollView) -> String?`
Takes **60 seconds**?!
It's depressing thinking about the wasted CPU cycles...

Thanks for running this Garvan! Sounds like we could save 2 minutes on builds just by refactoring those two lines.

**Comment by rnewman** [comment]
IIRC this is mostly due to string concats.

**Comment by rnewman** [comment]
I'll throw up a PR for `SQLiteLogins` this afternoon.

**Comment by rnewman** [comment]
Note that the double-compile stuff is fixed by recent project file changes in Bug 1239514.

**Comment by garvankeeley** [comment]
Just noticed comment you will be changing SQLiteLogins, I can remove that one

**Comment by rnewman** [comment]
Oh, hah, didn't notice this was a PR rather than an issue! Feel free to keep your fix, @garvankeeley.
