### ISSUE TITLE
can't search in bookmarks?

### ISSUE THREAD

**Issue by StefanoCecere** [mozilla/firefox-ios#1552]
since v1 up to this 2.0, we can't search in the bookmarks!

we use Firefox iOS mostly because of its sync with desktop
so we have all bookmarks synced. but if we can't search in them, they're useless!

am i wrong in anything?

iOS 9.2.1 on iPhone

**Comment by AaronMT** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1185038

**Comment by StefanoCecere** [comment]
:+1: thank you Aaron! 
it's a so basic feature that i was going mad about not making it work!

**Comment by StefanoCecere** [comment]
seems will be included in next release! [https://github.com/mozilla/firefox-ios/commit/ae949e63eb9f8d6fa302527131f0284246a3036c](https://github.com/mozilla/firefox-ios/commit/ae949e63eb9f8d6fa302527131f0284246a3036c)

**Comment by st3fan** [comment]
This is part of v4.0. If you want to test this functionality ahead of the release then please sign up for the TestFlight beta at https://docs.google.com/a/mozilla.com/forms/d/1VG9pOntPVhfZWH18ETAZDOahyA6SCbNEpCxBVI-XNJM/viewform
