### ISSUE TITLE
checkout.sh fail

### ISSUE THREAD

**Issue by ceekay1991** [mozilla/firefox-ios#1662]
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by AaronMT** [comment]
Still an issue?

**Comment by st3fan** [comment]
The `checkout.sh` script is deprecated in favor of `bootstrap.sh`. Please follow the instructions in the most recent `BUILDING.md`.
