### ISSUE TITLE
3rd Party Cookies Message Bug

### ISSUE THREAD

**Issue by XjSv** [mozilla/firefox-ios#1674]
When I visit the Sega support website and click "Login" via Firefox, I see this weird 3rd party cookie message. I do not see this message on Chrome or Safari. After filling the form and clicking "Sign in" nothing happens. Is this issue related with the browser or the website?

URL: https://support.sega.co.uk/hc/en-us

# **Firefox**
![Firefox](https://c2.staticflickr.com/2/1621/25841469790_f4552f91ef.jpg)

# **Chrome**
![Chrome](https://c2.staticflickr.com/2/1559/26088390726_dd7e8af4bb.jpg)

# **Safari**
![Safari](https://c2.staticflickr.com/2/1537/26021799242_64117e1924.jpg)

**Comment by Hi97** [comment]
Did you disable the cookies on Firefox?

**Comment by XjSv** [comment]
No, I did not. I checked again and the issue seems to have been fixed.
