### ISSUE TITLE
Skype protocol is not supported

### ISSUE THREAD

**Issue by zaabalonso** [mozilla/firefox-ios#1680]
Here is a demo button that works on safari but not on Firefox iOS browser.

http://codepen.io/anon/pen/QNMoYW

    window.location.href = 'skype:test?chat';

Firefox URI handling should handle skype: protocol.

**Comment by st3fan** [comment]
This should work in Firefox 3.0. What version did you test this on?

**Comment by zaabalonso** [comment]
true it works on 3.0 was broken on the previous version. We can close the issue :+1:
