### ISSUE TITLE
Clone down the code is missing a lot of files

### ISSUE THREAD

**Issue by AllLuckly** [mozilla/firefox-ios#1692]
Clone down the code is missing a lot of files  Xcode7.3

**Comment by sleroux** [comment]
Which files are you missing? Double check that you ran the checkout script in the root directory to pull down any missing dependencies by running `./checkout.sh`.

**Comment by AllLuckly** [comment]
hello！There has been the following:

`A shell task failed with exit code 128:
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out`

How to solve？

**Comment by sleroux** [comment]
Hm I don't recall having that as a dependency in the project. Maybe try recloning a fresh copy of the repo?

**Comment by aaronraimist** [comment]
This is the same error as  #1662. Also I believe you run ```./bootstrap.sh``` now instead of ```./checkout.sh```.

**Comment by yayang** [comment]
using ./checkout.sh still meet the same problem.

**Comment by st3fan** [comment]
@yayang @AllLuckly Can you please do the following and let us know if that works or not:

```
brew update
brew upgrade
brew install carthage 

git clone https://github.com/mozilla/firefox-ios
cd firefox-ios

./bootstrap.sh
```

After that you can open `Client.xcodeproj` and build and run the app. Try running in the *Simulator* first.

(This is essentially what BUILDING.md documents to be our build process.)

**Comment by st3fan** [comment]
(Please open this issue again if the BUILDING.md instructions do not work for you )
