### ISSUE TITLE
confused about the decode method of the search box of topright position on the desktop firefix browser

### ISSUE THREAD

**Issue by chenzhikang** [mozilla/firefox-ios#1694]
@thebnich  hello,sorry to interrupt you.but i was confused by the firefox broswer·s search input box of desktop.although this project is bind to firefox-ios,i think maybe you know the encode and decode method about input text of the  desktop`s searchbox .i will be thankful if u konw what i am talking about.

**Comment by thebnich** [comment]
Hi @chenzhikang,

As you mentioned, this project is for Firefox on iOS, so we won't be much help for desktop-specific questions. If you have an issue, you can file a desktop bug [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox). Or, if you just have a question, you can try asking the `#fx-team` channel on Mozilla's IRC network (irc.mozilla.org).
