### ISSUE TITLE
alternative keyboard prediction faillure...

### ISSUE THREAD

**Issue by nicomarti83** [mozilla/firefox-ios#1920]
hi,
I've got a problem with FF last version 4.0(11), when I type words in the search barre with swiftkey keyboard the prediction going crazy (predicted words have no links with typing words)... it's very disturbing... 

in this screenshot I type "when" in the FF search barre and the keyboard propose me "the" "de" "to"
![img_4135](https://cloud.githubusercontent.com/assets/18363363/16131723/f4861404-340f-11e6-8571-51581d5fd722.PNG)

in this screenshot I also type "when" but in a google page and the prediction work fine....
![img_4137](https://cloud.githubusercontent.com/assets/18363363/16132583/0b0727aa-3414-11e6-8979-82152a56d9b4.PNG)

sorry for gigantic pictures...

**Comment by varkor** [comment]
This issue is currently being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1209052, so that's a better way to keep an eye on what's going on with this one!
