### ISSUE TITLE
Can we rebrand the firefox with a new name and icon?

### ISSUE THREAD

**Issue by sumitjain7** [mozilla/firefox-ios#1981]
Hi Mozilla,

We want to rebrand Mozilla Firefox for iOS. We want to change the name, icon and useragent string and ask user to download it for free. Can we do so?

**Comment by jhugman** [comment]
Hey Sumitjain7

You wouldn't be the first!

The code is open source licensed under the [Mozilla Public Licence][1]. You should probably be aware of our [trademark policy][2] too. If comply with those two, I don't think you need any further permission.

But why fork, when you can contribute, and have far more users run your code? Come talk to us in [#mobile][3] to see how we can help.

[1]: https://www.mozilla.org/en-US/MPL/
[2]: https://www.mozilla.org/en-US/foundation/trademarks/policy/
[3]: https://wiki.mozilla.org/IRC
