### ISSUE TITLE
Feature Request: Integration with Siri

### ISSUE THREAD

**Issue by CodeforEvolution** [mozilla/firefox-ios#1996]
With iOS 10 coming out this fall, there are many new apis for apps to use. My idea is to take advantage of the new functions in SiriKit which allows apps to add there owns commands to Siri. I was think of something like: Siri, search with Firefox "What they want to search". Hope the team considers this. Could be a way now to get a head start before the official iOS 10 release.

**Comment by The-Wolf312** [comment]
I'd like to see this too but the problem is Apple won't even sue the app for review until a public release of iOS 10 is made.

**Comment by CodeforEvolution** [comment]
I was thinking this could be a branch that could be merged when the time comes, though you do have a good point otherwise.

**Comment by varkor** [comment]
The problem with opening up functionality such as search from Firefox via Siri is that SiriKit (at present) only supports a limited number of specific use cases (such as making payments, or ride-booking), none of which really overlap with Firefox use (photo search being the one possibly most relevant). It's hard to see what useful features could actually be integrated here without more capabilities added to SiriKit.
