### ISSUE TITLE
Feature Request: Add a Firefox URL Scheme

### ISSUE THREAD

**Issue by The-Wolf312** [mozilla/firefox-ios#2036]
It would be awesome to see a URL scheme such as firefox://somewebpage.com to automatically open links in Firefox. I know you can't make it the default browser but I think this would bring it as close as possible under the current iOS limitations.

**Comment by varkor** [comment]
Right now, this is actually possible to do in some form with URLs of the form: `firefox://?url=http://mozilla.org/`, though as this isn't documented, it's probably not a safe behaviour to rely on as of now.

**Comment by The-Wolf312** [comment]
I'll close this for now, and if it changes can you please update this?
