### ISSUE TITLE
Swift Compiler Errors - SQLite

### ISSUE THREAD

**Issue by rohanaurora** [mozilla/firefox-ios#301]
Can you advise on how to fix these Swift compiler errors on Xcode 6.2 (Build: 6C131e)?

Followed steps from [Building the Code] (https://github.com/mozilla/firefox-ios#building-the-code).

![errors](https://cloud.githubusercontent.com/assets/5597604/6974944/c68aea3e-d95c-11e4-9983-893ab413889f.png)

**Comment by wesj** [comment]
You might need to clear all the Derived data in Swift (and clean the project)? http://stackoverflow.com/questions/18933321/deleting-contents-from-xcode-derived-data-folder

**Comment by rohanaurora** [comment]
@wesj Correct. Didn't even think about it or might have forgotten earlier. Too bad that, there are 8 warnings (dependency analysis etc.). But, I was able to build today.
