### ISSUE TITLE
How do I build for my physical device?  Code signing errors abound!

### ISSUE THREAD

**Issue by stulevine** [mozilla/firefox-ios#350]
Can anyone tell me how to build this so I can put it on my phone?  I'm a registered developer with a valid signing certificate.  However, a number of components of the source here are signed by a variety of other entities.  I could not find anything that could help me online.  And when I attempt to allow Xcode to fix the issue, it either reports and error or just crashes.

**Comment by ncalexan** [comment]
On Sun, Apr 19, 2015 at 6:03 AM, Stuart Levine <notifications@github.com>
wrote:

> Can anyone tell me how to build this so I can put it on my phone? I'm a
> registered developer with a valid signing certificate. However, a number of
> components of the source here are signed by a variety of other entities. I
> could not find anything that could help me online. And when I attempt to
> allow Xcode to fix the issue, it either reports and error or just crashes.
>
I think @st3fan and @kearwood may be able to help with this.  I'm not aware
of docs for this process yet.

**Comment by DomT4** [comment]
:+1: would love to know this as well. Also have a dev account and valid signing cert available, but Xcode hits errors as well.

**Comment by ilhanadiyaman** [comment]
I have used steps below to debug it on my phone. 
1. Go to [member center] (https://developer.apple.com/membercenter/index.action) and create a wildcard App ID. For example: com.fennec.*
2. Create a new development provisioning profile for your wildcard app id with your test device UDID included. Download and install it.
3. Open Xcode project and switch to projects settings.
4. Under the Build settings find Code Signing Entitlements and delete Debug entitlement for Client, ShareTo and SendTo targets.
5. Switch back to General tab, change bundle identifier to com.fennec.Fennec for Client, ShareTo and SendTo target. Make sure you choose proper Team for your app id.
6. Build and run on your device.

**Comment by rnewman** [comment]
Sounds like that resolves this issue.

I'd ask that you not 'camp' any app IDs that you don't own — grab your own namespace.

**Comment by FrancisBaileyH** [comment]
I recently tried following these instructions and I run into an error

`An Application Group with Identifier 'group.org.mozilla.ios.Fennec' is not available. Please enter a different string.`

I'm not sure where to proceed from there. Any suggestions? I should also note there is another target 'ViewLater' that I had to change the bundle identifier for as well.
