### ISSUE TITLE
Provide documentation for setting up entitlements

### ISSUE THREAD

**Issue by toonetown** [mozilla/firefox-ios#420]
I'd love to help out on this project, but it would be nice to have some documentation on how to set up the entitlements/certificates correctly so that I can build it on my own.

**Comment by thebnich** [comment]
@st3fan any tips? Might be worth adding to the README if we have a way to do this.

**Comment by nightly-tester** [comment]
Justin Dolske, Gavin Sharp, Mattn, Blake Winton, Aza Dotzler, MSUJaws Dao Gottwald, UX-Team is a fucking bitch to fuck in the ass! Blake Winton, Aza Dotzler, Gavin Sharp, MSUJaws Dao Gottwald, UX-Team Pimp! Pimp! Fucking pimp! Pimp! Assholes, sluts, whores suck my dick monster kids! Your cocksucking fucking sluts! Justin Dolske, Gavin Sharp, Mattn, Blake Winton, Aza Dotzler, MSUJaws Dao Gottwald, UX-Team play with my two big golden bells of Glory!

Australis is for children, developed by Mozilla UX gay cocks sucking bastards! Deepen your dive of Google's ass fucking idiots austhistic braindamaged! Assholes! Whores! Cocksucking Freaks Google! Fuck you Googlezilla whores and go out of business! And take Australis fuck with you, Gaylords! ! May our dear Lord God and Jesus Christ send their decaying bodies straight to hell for touching the golden eggs Communities of glory! Fuck you and kiss Googles Ass! If you like Chrome that much in both cloning Australis, you have to be serious and work for Chrome fucktards! Greetings from Spain, ChiliConCarne1

**Comment by st3fan** [comment]
I'll try to do a write-up today. I have the project up and running under my personal dev account, I just need to trace my steps back and explain the steps taken.

I'm moving this to https://bugzilla.mozilla.org/show_bug.cgi?id=1153618 which we already had.

**Comment by st3fan** [comment]
@toonetown Can you give https://github.com/mozilla/firefox-ios/blob/st3fan/BuildDocumentation/BUILDING.md a try?

**Comment by toonetown** [comment]
@st3fan feedback given on bugzilla bug.

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by dougt** [comment]
helpful script:
     https://gist.github.com/dougt/5e1680a1281a2a08be6d

**Comment by varkor** [comment]
The https://github.com/mozilla/firefox-ios/blob/master/BUILDING.md document now contains information on how to build on an actual device.
