### ISSUE TITLE
Hijo de puta

### ISSUE THREAD

**Issue by TrashbinPornoDolske** [mozilla/firefox-ios#443]
You can lick my Penis and my golden Eggs, and kiss my Ass son of a bitch with a personality Disorder from the deepest pits of hell from the Depths of Mozilla!

Fuck you and your Mother you autistic son of a bitch, you're going to lick Putin's Eggs, Fucking Faggot Fascist!

The shit out of your Dog, your Cat and your dirty mountain Goat that Faggot Asshole!

Sucking Mozilla Cocks and all together go and suck on Google's Ass full of Shit!

To fuck in your knee you cock suckers! And who the Fuck Australis Chrome clone of shit! Fucking Mozilla gay lesbian homosexual bastards of hell!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!
