### ISSUE TITLE
Question on same-origin policy (SOP) across iframes

### ISSUE THREAD

**Issue by paragmajum** [mozilla/firefox-ios#548]
Does `firefox-ios`'s webkit implementation allow access to web preferences so that one can disable SOP across iframes that have different origins? Or is it just a view controller (or some kind of wrapper) built over the standard iOS Webkit library?

**Comment by st3fan** [comment]
We use the built-in `WKWebView`. I am curious why you ask. Do you have an interest in disabling the Same-Origin Policy or have you found a case where it fails to enforce it?
