### ISSUE TITLE
Add Upload support

### ISSUE THREAD

**Issue by ghost** [mozilla/firefox-ios#569]
yes really add this for iOS. 
See from iCab Mobile
http://www.icab-mobile.de/faq.html

Show by (Why are there issues uploading files?)

**Comment by st3fan** [comment]
Can you explain a bit more about the use-case for this feature? I will then create a more complete Bugzilla bug for it.

**Comment by Batteriee** [comment]
@st3fan 
Here a bug report from user
https://bugzilla.mozilla.org/show_bug.cgi?id=1172287

The app iCab mobile (third party app) is really nice in app store. Have many many functions. Can you copy the idea from third party app?

**Comment by varkor** [comment]
It seems what you're suggesting is to actually build in a file manager into the browser? This would most likely be the only way to achieve what you're requesting. It's unlikely that this would be something worth the time it would take to develop — this seems like an edge feature.
If you have any further comments, the Bugzilla report is a good place to follow up!
