### ISSUE TITLE
Recommendation: Add Handoff Support for Firefox on OSX and the iOS App

### ISSUE THREAD

**Issue by jaredStef** [mozilla/firefox-ios#577]
It would be nice if Firefox could hand-off your tabs from your mac to your iPhone and vice versa. Other browsers have this feature and it would be nice for Firefox to have as well.

**Comment by AaronMT** [comment]
We have a bug open here on Bugzilla with some initial thoughts and discussion https://bugzilla.mozilla.org/show_bug.cgi?id=1109806

**Comment by BigxMac** [comment]
I was on IRC and it was mentioned that the iOS and Firefox teams would both have to work together in order to get this to work

**Comment by BigBoneDaddy** [comment]
@BigxMac That great news! They say when it happen to happen?

**Comment by BigxMac** [comment]
There was no set date. You can ask on irc.mozilla.org on the #mobile channel. There may be an open big on bugzilla

**Comment by st3fan** [comment]
(Closing because we track this one in Bugzilla)
