### ISSUE TITLE
Fix http://git.chromium.org/webm/libwebp.git/info/refs not valid

### ISSUE THREAD

**Issue by joelchen** [mozilla/firefox-ios#589]
For people experiencing `http://git.chromium.org/webm/libwebp.git/info/refs not valid` when performing `sh update.sh`, modify your Cartfile's SDWebImage repository to the following will fix the issue:
```
git "https://github.com/joelchen/SDWebImage.git" "master"
```

**Comment by st3fan** [comment]
Thanks joel. Before we change this, lets wait a day or two and see if a new SDWebImage release comes out.

**Comment by BigBoneDaddy** [comment]
@st3fan @joelchen  It has been more than day or two lol! Is this still problem?
