### ISSUE TITLE
Reduce Sync size in Settings

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/firefox-ios#599]
A friendly suggestion from the Sync team. @darrinhenein thoughts?
![firefox-ios-sync](https://cloud.githubusercontent.com/assets/68213/8137380/02c70c9e-1111-11e5-92cc-bca51a3d8fb9.png)

**Comment by darrinhenein** [comment]
@ryanfeeley I filed this last week https://bugzilla.mozilla.org/show_bug.cgi?id=1171028

It's pretty much the same thin... can you comment there if it's not exactly what you want?
