### ISSUE TITLE
Firefox using signficant energy

### ISSUE THREAD

**Issue by UnicoRush** [mozilla/firefox-ios#601]
Hi,

Unlikely I am not a contributor to firefox, but I have noticed an issue that made me feel really sad and that's why I am posting here.

Firefox app uses so much CPU, which means my macbook pro is heating so much, that i have to stopped using it. Even when I am at home connected to power source I prefer not to use it, because of uncomfortable warm keyboard and fan screaming. Not to say outside w/o power source, when my battery lasts 2 hours.
Is there any way to fix it?

There is thread at bugzilla about this problem:
https://bugzilla.mozilla.org/show_bug.cgi?id=930586

Sincerely,
UnicoRush

**Comment by thebnich** [comment]
Thanks for the report, but this GitHub repo is for Firefox on iOS (mobile devices). It looks like you found the bug for this issue, so that's the best place to watch for updates.
