### ISSUE TITLE
Make it a Universal App

### ISSUE THREAD

**Issue by palewar** [mozilla/firefox-ios#67]
I am wondering why the existing client is just iPhone only? I think we can easily change it to a universal app using Autolayouts?

**Comment by rnewman** [comment]
Most of the design hasn't even been nailed down yet. We'll be supporting iPad eventually.

**Comment by soulwind** [comment]
Can I upload my own modified version of this project to Appstore?

Thank you

**Comment by andreasgal** [comment]
It's open source! Yes you can but you can't use the Firefox name or logo. If you make your own branding you are welcome to fork this and publish it anywhere you like.

**Comment by rnewman** [comment]
And we encourage you to open pull requests for any work you do that you'd like to incorporate into the mainline.

**Comment by soulwind** [comment]
I understood it
Can I use some name like Firefox Unofficial ?
Thank you

**Comment by andreasgal** [comment]
You cannot use the name "Firefox" or the Firefox logos (or Mozilla) in any form or shape but you are welcome to make up your own brand and logo. Be creative! Good luck with your project.
