### ISSUE TITLE
Test on Device

### ISSUE THREAD

**Issue by reza-ryte-club** [mozilla/firefox-ios#704]
I've signed iOS device for testing, when I try to run firefox from iOS simulator, it works perfectly. But when I want to test on device, I shows signing error. 

Check dependencies

** Code Sign error: No matching provisioning profiles found: None of the valid provisioning profiles allowed the specified entitlements: com.apple.security.application-groups, keychain-access-groups.
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file '/Users/rahmanmdrezaur/code/firefox-ios/Extensions/ViewLater/Info.plist'.
CodeSign error: code signing is required for product type 'App Extension' in SDK 'iOS 8.4'

No matching provisioning profiles found: None of the valid provisioning profiles allowed the specified entitlements: com.apple.security.application-groups, keychain-access-groups.

CodeSign error: code signing is required for product type 'App Extension' in SDK 'iOS 8.4' **

**Comment by ryanolsonx** [comment]
check out https://github.com/mozilla/firefox-ios/blob/master/BUILDING.md and make sure that you follow all of the steps outlined in the section "Run on a Device"

**Comment by reza-ryte-club** [comment]
Thanks.
