### ISSUE TITLE
Xcode 7, building...

### ISSUE THREAD

**Issue by ArielAbreu** [mozilla/firefox-ios#793]
So, I'm a beta tester for OSX 10.11 and iOS 9.0, and I was interested in this project and decided to build it. I've got an iPad Mini (1st Gen, armv7, running iOS 9, like I said) and an iMac Mid 2011-ish or something (running OSX 10.11) and Xcode 6.4 is no longer supported on OSX 10.11, so I downloaded the Xcode 7 beta, but I can't get firefox-ios to build. I've installed Carthage, and I ran `sh ./checkout.sh`, so it's not that (I think). First of all, I get lots of `Linker command failed with exit code 1` errors:
```
For Account:
ld: file not found: /Users/.../Library/Developer/Xcode/DerivedData/Client-bzciiebpmlbacuafrxtvtaueubcl/Build/Intermediates/SwiftMigration/Client/Intermediates/Client.build/Debug-iphoneos/Account.build/Objects-normal/armv7/FirefoxAccountConfiguration.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

For XCLogger:
ld: file not found: /Users/.../Library/Developer/Xcode/DerivedData/Client-bzciiebpmlbacuafrxtvtaueubcl/Build/Intermediates/SwiftMigration/Client/Intermediates/XCGLogger.build/Debug-iphoneos/XCGLogger (iOS).build/Objects-normal/armv7/XCGLogger.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And on, and on...
```
And it doesn't fail on these errors, nope. It keeps going on and hangs on the build for `Storage` at `Compiling Swift source files`.

I even get lots of nice little yellow warnings telling me that `Call to an error throwing function cannot be converted`!

Any ideas/help? It is a problem you're going to have to solve, because eventually iOS 9 will become a release and so will OSX El Capitan.

**Comment by AaronMT** [comment]
We currently do not build with Swift 2.0 and XCode 7. This is known.

**Comment by ArielAbreu** [comment]
Ok, thanks anyway.

**Comment by ArielAbreu** [comment]
Checked back on this, saw it was finally upgraded to Swift 2.0 and Xcode 7!
