### ISSUE TITLE
Build fails because of Storage framework

### ISSUE THREAD

**Issue by revolter** [mozilla/firefox-ios#854]
When I try to build the project, I get this error:

```
ld: framework not found Storage for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Framework not found Storage for architecture arm64
```

**Comment by rnewman** [comment]
Did you try a Clean build? Sometimes missing artifacts like this are resolved by just building a couple of times and hoping for the best.

**Comment by revolter** [comment]
I think it fixed it. But now, a short question, how to run it on device? Do you provide some development provisioning profiles?

**Comment by rnewman** [comment]
See 'Run on a Device' here: https://github.com/mozilla/firefox-ios/blob/master/BUILDING.md
