### ISSUE TITLE
Add support for gamepad

### ISSUE THREAD

**Issue by beaufortfrancois** [mozilla/firefox-ios#952]
How about adding support for the [Gamepad API](http://www.w3.org/TR/gamepad/)?

It looks as simple as injecting `navigator.getGamepads` and forwarding events to the UA.
See https://developer.mozilla.org/en-US/docs/Web/Guide/API/Gamepad

![](http://media.giphy.com/media/PK5CQPd6rCF3y/giphy.gif)

**Comment by AaronMT** [comment]
Firefox for iOS uses WKWebView (Webkit); GamePad is not implemented.

**Comment by beaufortfrancois** [comment]
From what I understood, WKWebView does not prevent UA to inject JS scripts. Therefore it should be able to implement a Gamepad library in Firefox for iOS.

cc @jyaif who might be interested.

**Comment by jyaif** [comment]
Like @beaufortfrancois said, you can inject "user scripts" before the pages are loaded. With those scripts you can, for instance, define navigator.getGamepads so that it returns an empty array.
Once gamepads are connected to the iOS device, swift code would execute javascript in the WKWebview so that getGamepads return up to date data.

**Comment by st3fan** [comment]
@jyaif Where are these Gamepad APIs documented? Is this something common in other browsers?

**Comment by jyaif** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

This API is available in most desktop browsers and a couple mobile browsers.

On Sunday, 1 May 2016, Stefan Arentz <notifications@github.com> wrote:

> @jyaif <https://github.com/jyaif> Where are these Gamepad APIs
> documented? Is this something common in other browsers?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/firefox-ios/issues/952#issuecomment-216000136>
>


-- 

Jean-François Geyelin

**Comment by varkor** [comment]
There's now a bug tracking this: https://bugzilla.mozilla.org/show_bug.cgi?id=1291452, which will be a better way to keep track of gamepad support!
